# Read the Docs configuration file for Ollama Forge
# For details, see: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install --upgrade pip
      - python -c "import pathlib; docs_index = pathlib.Path('docs/index.md'); docs_index.exists() or exit('Missing docs/index.md')"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
  - htmlzip
