name: 🔢 Version Consistency Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ollama_forge/config.py'
      - 'version.py'
      - 'pyproject.toml'
      - 'setup.py'
      - 'setup.cfg'
      - '.github/workflows/version_check.yml'

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v3
        
      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: 🧪 Check version consistency
        run: |
          echo "🕵️ Checking version consistency across files..."
          # Extract version from config.py
          CONFIG_VERSION=$(grep -oP 'VERSION\s*=\s*["\']([^"\']+)["\']' ollama_forge/config.py | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "📊 Config version: $CONFIG_VERSION"
          
          # Extract version from pyproject.toml
          PYPROJECT_VERSION=$(grep -oP 'version\s*=\s*["\']([^"\']+)["\']' pyproject.toml | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "📦 Pyproject version: $PYPROJECT_VERSION"
          
          # Extract version from version.py if it exists
          if [ -f "version.py" ]; then
            VERSION_PY_VERSION=$(grep -oP '__version__\s*=\s*["\']([^"\']+)["\']' version.py | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
            echo "🏷️ Version.py version: $VERSION_PY_VERSION"
            
            # Check if version.py and config.py match
            if [ "$CONFIG_VERSION" != "$VERSION_PY_VERSION" ]; then
              echo "❌ Version mismatch: config.py ($CONFIG_VERSION) vs version.py ($VERSION_PY_VERSION)"
              exit 1
            fi
          fi
          
          # Check if config.py and pyproject.toml match
          if [ "$CONFIG_VERSION" != "$PYPROJECT_VERSION" ]; then
            echo "❌ Version mismatch: config.py ($CONFIG_VERSION) vs pyproject.toml ($PYPROJECT_VERSION)"
            exit 1
          fi
          
          echo "✅ All version references are consistent!"
